sudo: required
dist: focal
language: node_js
node_js:
  - 20
cache:
  npm: false
  directories:
    - "~/.pnpm-store"
before_install:
  - npm install --global corepack@latest
  - corepack enable
  - corepack prepare pnpm@latest-10 --activate
  - pnpm config set store-dir ~/.pnpm-store
branches:
  only:
    - master
install:
  - pnpm install
script:
- pnpm typecheck
- pnpm lint
- pnpm test
- pnpm build:package
notifications:
  slack:
    rooms:
     - enasetech:kCpjRaaLjiHMfDkzq5fkfrcU#serverless-ses-template
