Resources:
  Route53RecordSetGroup:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneId: ${self:custom.projectConfig.hostedZoneId}
      RecordSets:
        - Name: ${self:custom.projectConfig.domainConfig.sesAssetBucketDomain}
          Type: A
          AliasTarget:
            DNSName: !GetAtt CloudFrontDistribution.DomainName
            EvaluateTargetHealth: false
            # This is always the hosted zone ID when you create an alias record that routes traffic to a CloudFront distribution.
            # see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html#cfn-route53-aliastarget-hostedzoneid
            HostedZoneId: Z2FDTNDATAQYW2
        - Name: ${self:custom.projectConfig.domainConfig.sesAssetBucketDomain}
          Type: AAAA
          AliasTarget:
            DNSName: !GetAtt CloudFrontDistribution.DomainName
            EvaluateTargetHealth: false
            # This is always the hosted zone ID when you create an alias record that routes traffic to a CloudFront distribution.
            # see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-route53-aliastarget.html#cfn-route53-aliastarget-hostedzoneid
            HostedZoneId: Z2FDTNDATAQYW2
